const COUNTRIES = [
  {name: "Afghanistan", capital: "Kabul", flag: "./flag_images/afghanistan.png"},
  {name: "Albania", capital: "Tirana", flag: "./flag_images/albania.png"},
  {name: "Algeria", capital: "Algiera", flag: "./flag_images/algeria.png"},
  {name: "Andorra", capital: "Andorra la Vella", flag: "./flag_images/andorra.png"},
  {name: "Angola", capital: "Luanda", flag: "./flag_images/angola.png"},
  {name: "Antigua and Barbuda", capital: "Saint John's", flag: "./flag_images/antigua_and_barbuda.png"},
  {name: "Argentina", capital: "Buenos Aires", flag: "./flag_images/argentina.png"},
  {name: "Armenia", capital: "Yerevan", flag: "./flag_images/armenia.png"},
  {name: "Aruba", capital: "Oranjestad", flag: "./flag_images/aruba.png"},
  {name: "Australia", capital: "Canberra", flag: "./flag_images/australia.png"},
  {name: "Austria", capital: "Vienna", flag: "./flag_images/austria.png"},
  {name: "Azerbaijan", capital: "Baku", flag: "./flag_images/azerbaijan.png"},
  {name: "Bahamas", capital: "Nassau", flag: "./flag_images/bahamas.png"},
  {name: "Bahrain", capital: "Manama", flag: "./flag_images/bahrain.png"},
  {name: "Bangladesh", capital: "Dhaka", flag: "./flag_images/bangladesh.png"},
  {name: "Barbados", capital: "Bridgetown", flag: "./flag_images/barbados.png"},
  {name: "Belarus", capital: "Minsk", flag: "./flag_images/belarus.png"},
  {name: "Belgium", capital: "Brussels", flag: "./flag_images/belgium.png"},
  {name: "Belize", capital: "Belmopan", flag: "./flag_images/belize.png"},
  {name: "Benin", capital: "Porto Novo", flag: "./flag_images/benin.png"},
  {name: "Bhutan", capital: "Thimphu", flag: "./flag_images/bhutan.png"},
  {name: "Bolivia", capital: "Sucre", flag: "./flag_images/bolivia.png"},
  {name: "Bosnia and Herzegovina", capital: "Sarajevo", flag: "./flag_images/bosnia_and_herzegovina.png"},
  {name: "Botswana", capital: "Gaborone", flag: "./flag_images/botswana.png"},
  {name: "Brazil", capital: "Brasilia", flag: "./flag_images/brazil.png"},
  {name: "Brunei", capital: "Bandar Seri Begawan", flag: "./flag_images/brunei.png"},
  {name: "Bulgaria", capital: "Sofia", flag: "./flag_images/bulgaria.png"},
  {name: "Burkina Faso", capital: "Ouagadougou", flag: "./flag_images/burkina_faso.png"},
  {name: "Burundi", capital: "Gitega", flag: "./flag_images/burundi.png"},
  {name: "Cambodia", capital: "Phnom Penh", flag: "./flag_images/cambodia.png"},
  {name: "Cameroon", capital: "Yaounde", flag: "./flag_images/cameroon.png"},
  {name: "Canada", capital: "Ottawa", flag: "./flag_images/canada.png"},
  {name: "Cape Verde", capital: "Praia", flag: "./flag_images/cape_verde.png"},
  {name: "Central African Republic", capital: "Bangui", flag: "./flag_images/car.png"},
  {name: "Chad", capital: "N'Djamena", flag: "./flag_images/chad.png"},
  {name: "Chile", capital: "Santiago", flag: "./flag_images/chile.png"},
  {name: "China", capital: "Beijing", flag: "./flag_images/china.png"},
  {name: "Colombia", capital: "Bogota", flag: "./flag_images/colombia.png"},
  {name: "Comoros", capital: "Moroni", flag: "./flag_images/comoros.png"},
  {name: "Costa Rica", capital: "San Jose", flag: "./flag_images/costa_rica.png"},
  {name: "Croatia", capital: "Zagreb", flag: "./flag_images/croatia.png"},
  {name: "Cuba", capital: "Havana", flag: "./flag_images/cuba.png"},
  {name: "Cyprus", capital: "Nicosia", flag: "./flag_images/cyprus.webp"},
  {name: "Czech Republic", capital: "Prague", flag: "./flag_images/czech_republic.png"},
  {name: "Democratic Republic of the Congo", capital: "Kinshasa", flag: "./flag_images/drc.png"},
  {name: "Denmark", capital: "Copenhagen", flag: "./flag_images/denmark.png"},
  {name: "Djibouti", capital: "Djibouti", flag: "./flag_images/djibouti.png"},
  {name: "Dominica", capital: "Roseau", flag: "./flag_images/dominica.png"},
  {name: "Dominican Republic", capital: "Santo Domingo", flag: "./flag_images/dominican_republic.png"},
  {name: "East Timor", capital: "Dili", flag: "./flag_images/east_timor.png"},
  {name: "Ecuador", capital: "Quito", flag: "./flag_images/ecuador.png"},
  {name: "Egypt", capital: "Cairo", flag: "./flag_images/egypt.png"},
  {name: "El Salvador", capital: "San Salvador", flag: "./flag_images/el_salvador.png"},
  {name: "Equatorial Guinea", capital: "Malabo", flag: "./flag_images/equatorial_guinea.png"},
  {name: "Eritrea", capital: "Asmara", flag: "./flag_images/eritrea.png"},
  {name: "Estonia", capital: "Tallinn", flag: "./flag_images/estonia.png"},
  {name: "Eswatini", capital: "Mbabane", flag: "./flag_images/eswatini.png"},
  {name: "Ethiopia", capital: "Addis Ababa", flag: "./flag_images/ethiopia.png"},
  {name: "Micronesia", capital: "Palikir", flag: "./flag_images/micronesia.png"},
  {name: "Fiji", capital: "Suva", flag: "./flag_images/fiji.png"},
  {name: "Finland", capital: "Helsinki", flag: "./flag_images/finland.png"},
  {name: "France", capital: "Paris", flag: "./flag_images/france.png"},
  {name: "Gabon", capital: "Libreville", flag: "./flag_images/gabon.png"},
  {name: "Gambia", capital: "Banjul", flag: "./flag_images/gambia.png"},
  {name: "Georgia", capital: "Tbilisi", flag: "./flag_images/georgia.png"},
  {name: "Germany", capital: "Berlin", flag: "./flag_images/germany.png"},
  {name: "Ghana", capital: "Accra", flag: "./flag_images/ghana.png"},
  {name: "Greece", capital: "Athens", flag: "./flag_images/greece.png"},
  {name: "Greenland", capital: "Nuuk", flag: "./flag_images/greenland.png"},
  {name: "Grenada", capital: "Saint George's", flag: "./flag_images/grenada.png"},
  {name: "Guatemala", capital: "Guatemala City", flag: "./flag_images/guatemala.png"},
  {name: "Guinea", capital: "Conakry", flag: "./flag_images/guinea.png"},
  {name: "Guinea Bissau", capital: "Bissau", flag: "./flag_images/guinea_bissau.png"},
  {name: "Guyana", capital: "Georgetown", flag: "./flag_images/guyana.png"},
  {name: "Haiti", capital: "Port au Prince", flag: "./flag_images/haiti.png"},
  {name: "Honduras", capital: "Tegucigalpa", flag: "./flag_images/honduras.png"},
  {name: "Hungary", capital: "Budapest", flag: "./flag_images/hungary.png"},
  {name: "Iceland", capital: "Reykjavik", flag: "./flag_images/iceland.png"},
  {name: "India", capital: "New Delhi", flag: "./flag_images/india.png"},
  {name: "Indonesia", capital: "Jakarta", flag: "./flag_images/indonesia.png"},
  {name: "Iran", capital: "Tehran", flag: "./flag_images/iran.png"},
  {name: "Iraq", capital: "Baghdad", flag: "./flag_images/iraq.png"},
  {name: "Ireland", capital: "Dublin", flag: "./flag_images/ireland.png"},
  {name: "Israel", capital: "Jerusalem", flag: "./flag_images/israel.png"},
  {name: "Italy", capital: "Rome", flag: "./flag_images/italy.png"},
  {name: "Ivory Coast", capital: "Yamoussoukro", flag: "./flag_images/ivory_coast.png"},
  {name: "Jamaica", capital: "Kingston", flag: "./flag_images/jamaica.png"},
  {name: "Japan", capital: "Tokyo", flag: "./flag_images/japan.png"},
  {name: "Jordan", capital: "Amman", flag: "./flag_images/jordan.png"},
  {name: "Kazakhstan", capital: "Astana", flag: "./flag_images/kazakhstan.png"},
  {name: "Kenya", capital: "Nairobi", flag: "./flag_images/kenya.png"},
  {name: "Kiribati", capital: "Tarawa Atoll", flag: "./flag_images/kiribati.png"},
  {name: "Kosovo", capital: "Pristina", flag: "./flag_images/kosovo.png"},
  {name: "Kuwait", capital: "Kuwait City", flag: "./flag_images/kuwait.png"},
  {name: "Kyrgyzstan", capital: "Bishkek", flag: "./flag_images/kyrgyzstan.png"},
  {name: "Laos", capital: "Vientiane", flag: "./flag_images/laos.png"},
  {name: "Latvia", capital: "Riga", flag: "./flag_images/latvia.png"},
  {name: "Lebanon", capital: "Beirut", flag: "./flag_images/lebanon.png"},
  {name: "Lesotho", capital: "Maseru", flag: "./flag_images/lesotho.png"},
  {name: "Liberia", capital: "Monrovia", flag: "./flag_images/liberia.png"},
  {name: "Libya", capital: "Tripoli", flag: "./flag_images/libya.png"},
  {name: "Liechtenstein", capital: "Vaduz", flag: "./flag_images/liechtenstein.png"},
  {name: "Lithuania", capital: "Vilnius", flag: "./flag_images/lithuania.png"},
  {name: "Luxembourg", capital: "Luxembourg", flag: "./flag_images/luxembourg.png"},
  {name: "Madagascar", capital: "Antananarivo", flag: "./flag_images/madagascar.png"},
  {name: "Malawi", capital: "Lilongwe", flag: "./flag_images/malawi.png"},
  {name: "Malaysia", capital: "Kuala Lumpur", flag: "./flag_images/malaysia.png"},
  {name: "Maldives", capital: "Male", flag: "./flag_images/maldives.png"},
  {name: "Mali", capital: "Bamako", flag: "./flag_images/mali.png"},
  {name: "Malta", capital: "Valletta", flag: "./flag_images/malta.png"},
  {name: "Marshall Islands", capital: "Majuro", flag: "./flag_images/marshall_islands.png"},
  {name: "Mauritania", capital: "Nouakchott", flag: "./flag_images/mauritania.png"},
  {name: "Mauritius", capital: "Port Louis", flag: "./flag_images/mauritius.png"},
  {name: "Mexico", capital: "Mexico City", flag: "./flag_images/mexico.png"},
  {name: "Moldova", capital: "Chisinau", flag: "./flag_images/moldova.png"},
  {name: "Monaco", capital: "Monaco", flag: "./flag_images/monaco.png"},
  {name: "Mongolia", capital: "Ulaanbaatar", flag: "./flag_images/mongolia.png"},
  {name: "Montenegro", capital: "Podgorica", flag: "./flag_images/montenegro.png"},
  {name: "Morocco", capital: "Rabat", flag: "./flag_images/morocco.png"},
  {name: "Mozambique", capital: "Maputo", flag: "./flag_images/mozambique.png"},
  {name: "Myanmar", capital: "Naypyidaw", flag: "./flag_images/myanmar.png"},
  {name: "Namibia", capital: "Windhoek", flag: "./flag_images/namibia.png"},
  {name: "Nauru", capital: "Yaren", flag: "./flag_images/nauru.png"},
  {name: "Nepal", capital: "Kathmandu", flag: "./flag_images/nepal.png"},
  {name: "Netherlands", capital: "Amsterdam", flag: "./flag_images/netherlands.png"},
  {name: "New Zealand", capital: "Wellington", flag: "./flag_images/new_zealand.png"},
  {name: "Nicaragua", capital: "Managua", flag: "./flag_images/nicaragua.png"},
  {name: "Niger", capital: "Niamey", flag: "./flag_images/niger.png"},
  {name: "Nigeria", capital: "Abuja", flag: "./flag_images/nigeria.png"},
  {name: "North Korea", capital: "Pyongyang", flag: "./flag_images/north_korea.png"},
  {name: "North Macedonia", capital: "Skopje", flag: "./flag_images/north_macedonia.png"},
  {name: "Norway", capital: "Oslo", flag: "./flag_images/norway.png"},
  {name: "Oman", capital: "Muscat", flag: "./flag_images/oman.png"},
  {name: "Pakistan", capital: "Islamabad", flag: "./flag_images/pakistan.png"},
  {name: "Palau", capital: "Ngerulmud", flag: "./flag_images/palau.png"},
  {name: "Palestine", capital: "Jerusalem", flag: "./flag_images/palestine.png"},
  {name: "Panama", capital: "Panama City", flag: "./flag_images/panama.png"},
  {name: "Papua New Guinea", capital: "Port Moresby", flag: "./flag_images/papua_new_guinea.png"},
  {name: "Paraguay", capital: "Asuncion", flag: "./flag_images/paraguay.png"},
  {name: "Peru", capital: "Lima", flag: "./flag_images/peru.png"},
  {name: "Philippines", capital: "Manila", flag: "./flag_images/philippines.png"},
  {name: "Poland", capital: "Warsaw", flag: "./flag_images/poland.png"},
  {name: "Portugal", capital: "Lisbon", flag: "./flag_images/portugal.png"},
  {name: "Qatar", capital: "Doha", flag: "./flag_images/qatar.png"},
  {name: "Republic of the Congo", capital: "Brazzaville", flag: "./flag_images/congo.png"},
  {name: "Romania", capital: "Bucharest", flag: "./flag_images/romania.png"},
  {name: "Russia", capital: "Moscow", flag: "./flag_images/russia.png"},
  {name: "Rwanda", capital: "Kigali", flag: "./flag_images/rwanda.png"},
  {name: "Saint Kitts and Nevis", capital: "Basseterre", flag: "./flag_images/saint_kitts_and_nevis.png"},
  {name: "Saint Lucia", capital: "Castries", flag: "./flag_images/saint_lucia.png"},
  {name: "Saint Vincent and the Grenadines", capital: "Kingstown", flag: "./flag_images/saint_vincent_and_the_grenadines.png"},
  {name: "Samoa", capital: "Apia", flag: "./flag_images/samoa.png"},
  {name: "San Marino", capital: "San Marino", flag: "./flag_images/san_marino.png"},
  {name: "Sao Tome and Principe", capital: "Sao Tome", flag: "./flag_images/sao_tome_and_principe.png"},
  {name: "Saudi Arabia", capital: "Riyadh", flag: "./flag_images/saudi_arabia.png"},
  {name: "Senegal", capital: "Dakar", flag: "./flag_images/senegal.png"},
  {name: "Serbia", capital: "Belgrade", flag: "./flag_images/serbia.png"},
  {name: "Seychelles", capital: "Victoria", flag: "./flag_images/seychelles.png"},
  {name: "Sierra Leone", capital: "Freetown", flag: "./flag_images/sierra_leone.png"},
  {name: "Singapore", capital: "Singapore", flag: "./flag_images/singapore.png"},
  {name: "Slovakia", capital: "Bratislava", flag: "./flag_images/slovakia.png"},
  {name: "Slovenia", capital: "Ljubljana", flag: "./flag_images/slovenia.png"},
  {name: "Solomon Islands", capital: "Honiara", flag: "./flag_images/solomon_islands.png"},
  {name: "Somalia", capital: "Mogadishu", flag: "./flag_images/somalia.png"},
  {name: "South Africa", capital: "Pretoria", flag: "./flag_images/south_africa.png"},
  {name: "South Korea", capital: "Seoul", flag: "./flag_images/south_korea.png"},
  {name: "South Sudan", capital: "Juba", flag: "./flag_images/south_sudan.png"},
  {name: "Spain", capital: "Madrid", flag: "./flag_images/spain.png"},
  {name: "Sri Lanka", capital: "Sri Jayawardenapura Kotte", flag: "./flag_images/sri_lanka.png"},
  {name: "Sudan", capital: "Khartoum", flag: "./flag_images/sudan.png"},
  {name: "Suriname", capital: "Paramaribo", flag: "./flag_images/suriname.png"},
  {name: "Sweden", capital: "Stockholm", flag: "./flag_images/sweden.png"},
  {name: "Switzerland", capital: "Bern", flag: "./flag_images/switzerland.png"},
  {name: "Syria", capital: "Damascus", flag: "./flag_images/syria.png"},
  {name: "Taiwan", capital: "Taipei", flag: "./flag_images/taiwan.png"},
  {name: "Tajikistan", capital: "Dushanbe", flag: "./flag_images/tajikistan.png"},
  {name: "Tanzania", capital: "Dodoma", flag: "./flag_images/tanzania.png"},
  {name: "Thailand", capital: "Bangkok", flag: "./flag_images/thailand.png"},
  {name: "Togo", capital: "Lome", flag: "./flag_images/togo.png"},
  {name: "Tonga", capital: "Nuku'alofa", flag: "./flag_images/tonga.png"},
  {name: "Trinidad and Tobago", capital: "Port of Spain", flag: "./flag_images/trinidad_and_tobago.png"},
  {name: "Tunisia", capital: "Tunis", flag: "./flag_images/tunisia.png"},
  {name: "Turkey", capital: "Ankara", flag: "./flag_images/turkey.png"},
  {name: "Turkmenistan", capital: "Ashgabat", flag: "./flag_images/turkmenistan.png"},
  {name: "Tuvalu", capital: "Funafuti", flag: "./flag_images/tuvalu.png"},
  {name: "Uganda", capital: "Kampala", flag: "./flag_images/uganda.png"},
  {name: "Ukraine", capital: "Kyiv", flag: "./flag_images/ukraine.png"},
  {name: "United Arab Emirates", capital: "Abu Dhabi", flag: "./flag_images/uae.png"},
  {name: "United Kingdom", capital: "London", flag: "./flag_images/uk.png"},
  {name: "United States of America", capital: "Washington D.C.", flag: "./flag_images/usa.png"},
  {name: "Uruguay", capital: "Montevideo", flag: "./flag_images/uruguay.png"},
  {name: "Uzbekistan", capital: "Tashkent", flag: "./flag_images/uzbekistan.png"},
  {name: "Vanuatu", capital: "Port Vila", flag: "./flag_images/vanuatu.png"},
  {name: "Vatican City", capital: "does not exist.", flag: "./flag_images/vatican_city.png"},
  {name: "Venezuela", capital: "Caracas", flag: "./flag_images/venezuela.png"},
  {name: "Vietnam", capital: "Hanoi", flag: "./flag_images/vietnam.png"},
  {name: "Yemen", capital: "Sanaa", flag: "./flag_images/yemen.png"},
  {name: "Zambia", capital: "Lusaka", flag: "./flag_images/zambia.jpeg"},
  {name: "Zimbabwe", capital: "Harare", flag: "./flag_images/zimbabwe.png"},
];